[package]
name = "rust-github-assistant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
# serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
